"""Initial Commit

Revision ID: 73fe7d6a499f
Revises: 
Create Date: 2025-03-18 15:29:15.052119

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '73fe7d6a499f'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('user_ID', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('first_name', sa.String(length=100), nullable=False),
    sa.Column('second_name', sa.String(length=100), nullable=False),
    sa.Column('username', sa.String(length=100), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('user_ID'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('username')
    )
    op.create_table('ai_responses',
    sa.Column('response_ID', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_ID', sa.Integer(), nullable=False),
    sa.Column('scenario_ID', sa.Integer(), nullable=False),
    sa.Column('IS_correct', sa.Boolean(), nullable=False),
    sa.Column('attempt_number', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_ID'], ['users.user_ID'], ),
    sa.PrimaryKeyConstraint('response_ID')
    )
    op.create_table('badges',
    sa.Column('badge_ID', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_ID', sa.Integer(), nullable=False),
    sa.Column('badge_name', sa.String(length=100), nullable=False),
    sa.Column('score', sa.Integer(), nullable=False),
    sa.Column('number_of_attempts', sa.Integer(), nullable=True),
    sa.Column('progress', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['user_ID'], ['users.user_ID'], ),
    sa.PrimaryKeyConstraint('badge_ID')
    )
    op.create_table('game_stages',
    sa.Column('stage_ID', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_ID', sa.Integer(), nullable=False),
    sa.Column('stage_name', sa.Enum('Preconception', 'Antenatal', 'Birth', 'Postnatal'), nullable=False),
    sa.Column('number_of_attempts', sa.Integer(), nullable=True),
    sa.Column('overall_score', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_ID'], ['users.user_ID'], ),
    sa.PrimaryKeyConstraint('stage_ID')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('game_stages')
    op.drop_table('badges')
    op.drop_table('ai_responses')
    op.drop_table('users')
    # ### end Alembic commands ###
